### PR TITLE
#109 Clipping Fix

### PR DESCRIPTION
**Pull request by CursedGamerZ**
Fixes clipping, Multiple resizing of the window showed no signs of interfering or overlapping of shaka player from other elements.
closes https://github.com/clipable/clipable/issues/109

### CODE REVIEW

**Review by CameronLehr — APPROVED** [review]

**Comment by ImVexed** [comment]
image

This still breaks for thumbnails. Also, why are we setting other elements to be below the dropdown, when we can just set the dropdown to be above everything else?

**Comment by ImVexed** [comment]
Also, it would help if the branch had a meaningful name, not just your name

**Comment by CursedGamerZ** [comment]
firefox_msOyAbeuMr
firefox_m6N1ZY9KTd
Fixed Z-index of header items and reverted changes to the shaka player index. Sorry misunderstood workflow of naming branches, wont happen again.

**Comment by CursedGamerZ** [comment]
> ![image](https://user-images.githubusercontent.com/10090878/222328036-3f29aea1-0df0-4762-ad8b-61f7a386998f.png

**Review by CursedGamerZ — COMMENTED** [review]
firefox_msOyAbeuMr
firefox_m6N1ZY9KTd

**Review by puckzxz — APPROVED** [review]

**Pull request merged**
