### PR TITLE
Wrap backend errors

### PR DESCRIPTION
**Pull request by Mihai22125**
resolves: #56

First time contributor, any feedback would be more than appreciated.

### CODE REVIEW

**Comment by ImVexed** [comment]
I like the direction this is going! Wrapping errors into a json object was indeed something we need to do, I originally only intended this to wrap 500 errors with additional context so you could tell what was failing in the console logs when you got an `io.EOF`. 

I think the next step here is to port this to our current style of wrapping `http.HandlerFunc`'s as we do in most of the routes. It's not done in the files you touched because they either A: Manipulate Headers, or B: return a Stream. It's important we keep this style because it makes testing significantly easier as we're just returning errors and http status codes instead of full serialized `ResponseWriter`s. 

So from my perspective there's 2 things we need to do here:
- Make an overload of [r.Auth](https://github.com/clipable/clipable/blob/master/backend/routes/middleware.go#L24) accepts `(int, io.ReadCloser, http.Header, error)` and use that for all of the routes that currently can't use `r.Auth` 
- Transition the `handleErr` logic you wrote into https://github.com/clipable/clipable/blob/master/backend/routes/middleware.go#L61 that way all routes can take advantage of serializing errors into json objects

If you'd like I can handle making the overload of `r.Auth` as there will probably be edge cases with how we handle closing readers from minio as well as needing direct access to the `ResponseWriter` while writing to the session. Then you could just pull in that change and handle updating the return statements inside of `routes/` to be detailed enough to mean something when they're logged.

**Comment by ImVexed** [comment]
@Mihai22125 I've created https://github.com/clipable/clipable/pull/71 as mentioned in my previous comment. This better sets you up to convert us to JSON serialization of error messages since all routes now pass through the same generic middleware.

For example:
 - https://github.com/clipable/clipable/blob/e4120845ed337810060efb4b729ab7dc39964740/backend/routes/auth.go#L24 Here you could change `[]byte(err.Error())` to serialize a JSON error object. Ideally the error object/serialization helper functions would live in `modelsx/`
 - Here is another example of the `InternalServerError` wrapping I originally intended this to solve https://github.com/clipable/clipable/blob/e4120845ed337810060efb4b729ab7dc39964740/backend/routes/auth.go#L32 You can see here we properly wrap the `err` with additional context about what we were trying to do when it failed, so we don't just see a `/login status:500 err: Connection timed out` and have to guess what part of the route failed, as we'd instead see: `/login status:500 err: Failed to fetch user: Connection timed out`

**Comment by Mihai22125** [comment]
Hello @ImVexed!

Thank you for your feedback and detailed explanation of the next steps for this PR. I appreciate your guidance on how to improve the current implementation and make it more consistent with the current style of wrapping http.HandlerFuncs.

As for transitioning the handleErr logic into middleware.go, I agree that it's important to keep a consistent style and make testing easier.

Thanks for providing the examples in auth.go, they are very helpful in understanding how to properly wrap errors with additional context. I'll make sure to apply the same wrapping logic to all other routes files. I'll keep you updated on my progress.

**Comment by ImVexed** [comment]
Hey @Mihai22125 Just wanted to check up if you're having any issues! We're looking at an initial MVP on https://github.com/clipable/clipable/milestone/1 (Feb, 28th). So, if things get close, we'll probably end up having our team complete this in a separate PR.

**Comment by ImVexed** [comment]
This issue has been closed now @Mihai22125 Sorry the timelines didn't match up here https://github.com/clipable/clipable/issues/56

**Pull request closed without merging**
